### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by shane0** [shane0/cheatsheets#15]
# react mongo

In this example, we have two services defined: react-app and mongo-db.

The react-app service:

Builds the React app image using the Dockerfile in the current directory (denoted by .)
Maps port 3000 in the container to port 3000 on the host
Mounts the current directory as a volume in the container (this allows live reloading of code changes without having to rebuild the image)
Sets the NODE_ENV environment variable to development
Specifies that it depends on the mongo-db service (so that it won't start until the MongoDB service is running)
The mongo-db service:

Uses the mongo image from Docker Hub
Maps port 27017 in the container to port 27017 on the host
Mounts the ./data directory as a volume in the container (this is where the database files will be stored)
Sets the MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD environment variables (these will be used to create a superuser for the database)
To run this setup, navigate to the directory containing the docker-compose.yml file and run docker-compose up. This will start both services and you should be able to access the React app at http://localhost:3000.

`mongodb://mongo:27017/mydatabase`

```yml
version: "3"

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
```
